// Electron's documented manual distribution layout; no installer or signing step.
import { cp, mkdir, readFile, copyFile, unlink, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(fileURLToPath(new URL('../', import.meta.url)));
if (process.platform !== 'win32') throw new Error('This package target is Windows.');
const output = path.join(root, 'release', 'win-unpacked');
const electron = path.join(root, 'node_modules', 'electron', 'dist');
const engine = path.join(root, 'desktop', 'engine');
await stat(path.join(engine, 'python.exe'));
await stat(path.join(root, 'dist', 'index.html'));
await mkdir(output, { recursive: true });
await cp(electron, output, { recursive: true });
await copyFile(path.join(output, 'electron.exe'), path.join(output, 'EdgeLens.exe'));
await unlink(path.join(output, 'electron.exe'));
const resources = path.join(output, 'resources');
const appDir = path.join(resources, 'app');
await mkdir(path.join(appDir, 'desktop'), { recursive: true });
await copyFile(path.join(root, 'desktop', 'main.cjs'), path.join(appDir, 'desktop', 'main.cjs'));
const source = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
await writeFile(path.join(appDir, 'package.json'), JSON.stringify({ name: source.name, productName: 'EdgeLens', version: source.version, main: 'desktop/main.cjs' }, null, 2));
await cp(engine, path.join(resources, 'engine'), { recursive: true });
await cp(path.join(root, 'dist'), path.join(resources, 'ui'), { recursive: true });
await cp(path.join(root, 'docs'), path.join(output, 'docs'), { recursive: true });
await copyFile(path.join(root, 'desktop', 'icon.ico'), path.join(resources, 'icon.ico'));
await writeFile(path.join(output, 'READ ME.txt'), 'EdgeLens — Model Conversion Studio\r\n\r\nDouble-click EdgeLens.exe. Keep this entire folder together.\r\nPython, CPU ONNX, LiteRT inference and USB serial support are included.\r\nUpload your own trusted PT2, ONNX or TFLite classifier. Sample presets may download pretrained weights.\r\nYour data is saved in %APPDATA%\\EdgeLens\\data.\r\nTFLite conversion needs an optional Linux worker; it is unavailable here.\r\nThis is an unsigned portable prototype, not a signed installer.\r\n');
console.log(`Portable desktop application: ${path.join(output, 'EdgeLens.exe')}`);
